### PR TITLE
Point to version 2.0.0 of phantomjs

### PR DESCRIPTION
**Pull request by tmcgilchrist**

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
Not sure what's the deal with the windows version. I don't have access to anything running windows so debugging is going to be difficult.

**Comment by chuckd** [comment]
@tmcgilchrist I took a quick look inside phantomjs-2.0.0-windows.zip and it seems they moved phantomjs.exe into the bin folder, as per other platforms. Adding 'bin' to the path at line 152 of platform.rb should fix it:

    File.expand_path File.join(Phantomjs.base_dir, platform, 'bin', 'phantomjs.exe')

then updating platform_spec.rb at line 166:

    Phantomjs.path.should =~ /win32\/bin\/phantomjs.exe$/

I too lack access to a Windows installation with working Ruby, so haven't tested this...

(I can submit as a separate PR if you like but seems easier to update this one)

**Comment by meghan-mcqueeney** [comment]
I'd love to see this pull go through. We've been seeing issues with older versions of PhantomJS that we believe 2.0 could resolve. Any update on this?

**Comment by metaskills** [comment]
Can we re-open any version that pulls in the latest 2.0? We are stuck on that version.

**Pull request closed without merging**
