### PR TITLE
upgrade phantom to 2.0.0

### PR DESCRIPTION
**Pull request by joedivita**

### CODE REVIEW

**Comment by mtyeh411** [comment]
any reason this was closed? does anyone know the roadmap for when 2.0.0 would be used?

**Comment by joedivita** [comment]
I pulled the trigger on this a little too soon as PhantomJS has yet to release the official binaries for linux for 2.0.  Also, the binary they released for Max OSX doesn't work on Yosemite.  

On the latest rev on my fork I've linked to temporary self hosted binaries for linux and macosx that work on ubuntu14.04 (64 bit) & Yosemite that were compiled by eugene1g [linked here](https://github.com/eugene1g/phantomjs/releases) as temporary solutions until the official binaries are released.

**Comment by mtyeh411** [comment]
@joedivita makes sense.  thanks for the reply!

**Comment by lencioni** [comment]
It looks like there is a way to run 2.0 on Yosemite: https://github.com/ariya/phantomjs/issues/12900#issuecomment-74073057

**Comment by metaskills** [comment]
Can we re-open this?

**Comment by joedivita** [comment]
@metaskills Looks like they've already upgraded the master branch to v 2.1.1 for all platforms, no?:

https://github.com/colszowka/phantomjs-gem/blob/master/lib/phantomjs/platform.rb#L133

**Comment by metaskills** [comment]
They have... but I have a repo that needs 2.0.x

**Pull request closed without merging**
